# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('webgui/assets/', 'webgui/assets/'),
        ('../README.md', '.'),
    ],
    hiddenimports = [
    'cli',
    'config',
    'library_path_updater',
    'logger_config',
    'file_converter',
    'folder_structure_creator',
    'webgui',
    'webgui.app',
    'webgui.api',
    'webgui.log_bridge',
    'webview',
    'webview.platforms.winforms',
    'clr',
    'labware_sync',
    'email_log_handler',
    'file_operations',
    'monitoring',
    'csv_operations',
    'string_search',
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['msmpi.dll', 'ze_loader.dll', 'sycl6.dll', 'pgc.dll', 'pgf90.dll', 'pgmath.dll', 'impi.dll'],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Hamilton_Method_Versionator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['hamilton_versioning_logo.ico'],
)

# CLI executable — same entry point, but with console=True for terminal output
cli_exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Hamilton_Method_Versionator_cli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['hamilton_versioning_logo.ico'],
)
